---
- name: Generate registration command
  redhat.satellite.registration_command:
    smart_proxy: "capsule.shadowman.dev"
    insecure:
    setup_remote_execution: false
    setup_insights: false
    validate_certs: false
    update_packages: false
    setup_remote_execution_pull: false
    activation_keys:
      - "{{ operating_system }}"
  register: register_command
  when:
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"

- name: Perform registration
  ansible.builtin.shell:
    cmd: "{{ register_command.registration_command }}"
  when:
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"

- name: Use Activation Key to Register Azure RHEL Machine to RHSM
  community.general.redhat_subscription:
    state: present
    activationkey: "azure"
    org_id: "13247185"
  when: shadowman_provision_hypervisor | default('RHV') == "Azure"
  ignore_errors: true

- name: Enable Repositories for RHEL 7
  community.general.rhsm_repository:
    name:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
    purge: true
  when:
    - ansible_distribution_version is match("7.*")
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"

- name: Enable Repositories for RHEL 8 when not using Azure base image
  community.general.rhsm_repository:
    name:
      - rhel-8-for-x86_64-appstream-rpms
      - rhel-8-for-x86_64-baseos-rpms
    purge: true
  when:
    - ansible_distribution_version is match("8.*")
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"

- name: Enable Repositories for RHEL 9 when not using Azure base image
  community.general.rhsm_repository:
    name:
      - rhel-9-for-x86_64-appstream-rpms
      - rhel-9-for-x86_64-baseos-rpms
    purge: true
  when:
    - ansible_distribution_version is match("9.*")
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"
