---
- name: Get all of the Guest Info
  community.vmware.vmware_guest_info:
    validate_certs: false
    schema: vsphere
    name: "{{ inventory_hostname }}"
  register: info
  delegate_to: localhost

- name: Firmware Check
  ansible.builtin.assert:
    that: info.instance.config.firmware == "efi"
    fail_msg: Boot Firmware is not EFI

- name: Secure Boot Check
  ansible.builtin.assert:
    that: info.instance.config.bootOptions.efiSecureBootEnabled == True
    fail_msg: Secure Boot is Disabled

- name: VBS Check
  ansible.builtin.assert:
    that: info.instance.config.flags.vbsEnabled == True
    fail_msg: VBS is Disabled

- name: TPM Check
  ansible.builtin.assert:
    that: info.instance.summary.config.tpmPresent == False
    fail_msg: vTPM has already been added

- name: Output Pre-Reqs
  ansible.builtin.debug:
    msg: "Secure Boot: {{ info.instance.config.bootOptions.efiSecureBootEnabled }}, Firmware:{{ info.instance.config.firmware }}, VBS: {{ info.instance.config.flags.vbsEnabled }}, TPM: {{ info.instance.summary.config.tpmPresent }} VMWare Tools: {{ info.instance.guest.toolsStatus }} VMWare Tools Running: {{ info.instance.guest.toolsRunningStatus }}"
  delegate_to: localhost
